# NovaShop — Fluent Bit Log Toplayıcı ve Filtreleyici Yapılandırması
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

# 1. Giriş: Docker Konteyner Loglarını Oku
[INPUT]
    Name             forward
    Listen           0.0.0.0
    Port             24224

# 2. Filtre: JSON Loglarını Çözümle ve Trace-ID Korelasyonu Yap
[FILTER]
    Name             parser
    Match            *
    Key_Name         log
    Parser           json
    Reserve_Data     On

# 3. Çıkış: Logları Elasticsearch'e İndeksle
[OUTPUT]
    Name             es
    Match            *
    Host             elasticsearch
    Port             9200
    Index            novashop-logs
    Type             _doc
    Suppress_Type_Name On
    Trace_Error      On
