# NovaShop — Prometheus Metrik Toplama Yapılandırması
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # 1. Prometheus Kendi Metrikleri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. NovaShop UI Spring Boot Actuator Metrikleri
  - job_name: "novashop-ui"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["ui:8080"]

  # 3. NovaShop Mikroservis Metrikleri
  - job_name: "novashop-catalog"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["catalog:8080"]

  - job_name: "novashop-cart"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["cart:8080"]

  - job_name: "novashop-checkout"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["checkout:8080"]

  - job_name: "novashop-orders"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["orders:8080"]

  # 4. OpenTelemetry Collector Metrik Çıkışı
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # 5. Host & Konteyner İzleme (Docker Monitoring)
  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 10s
    static_configs:
      - targets: ["cadvisor:8080"]
